# Generated by Django 4.0.4 on 2022-06-07 19:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0012_title_remove_result_duplicate_descriptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateH1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, size=None)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_h1', to='spider.result')),
            ],
        ),
    ]
