# Generated by Django 4.0.4 on 2022-06-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0014_alter_lowmeta_result_alter_missingviewport_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlingstatistic',
            name='number_of_crawl',
        ),
    ]
