# Generated by Django 4.0.4 on 2022-06-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0016_remove_auditstatistic_number_of_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditstatistic',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='crawlingstatistic',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
