# Generated by Django 4.0.4 on 2022-06-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0018_article_articlecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecontent',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
