# Generated by Django 4.0.4 on 2022-06-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0019_articlecontent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auditing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='crawling',
            field=models.BooleanField(default=False),
        ),
    ]
